version: 2
project_name: SteamUpdateManager
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - windows
    goarch:
      - amd64
      - arm64
archives:
    format_overrides:
      - goos: windows
        format: zip
    files:
      - "*.md"
      - "LICENSE"
      - "*.json"