version: 2
project_name: SteamUpdateManager

before:
  hooks:
    - go mod tidy
    - go install github.com/fyne-io/fyne-cross@latest
    - fyne-cross windows -arch=amd64 -app-id com.looterz.steamupdatemanager -icon Icon.png -output SteamUpdateManager

builds:
  - skip: true

archives:
  - id: default
    format: zip
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
    files:
      - LICENSE
      - README.md
      - fyne-cross/bin/windows-amd64/SteamUpdateManager.exe

release:
  extra_files:
    - glob: ./fyne-cross/bin/windows-amd64/SteamUpdateManager.exe

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
