version: 2
project_name: SteamUpdateManager

before:
  hooks:
    - go mod tidy

builds:
  - id: windows-amd64
    binary: SteamUpdateManager
    env:
      - CGO_ENABLED=1
    goos:
      - windows
    goarch:
      - amd64
    hooks:
      pre:
        - go install github.com/fyne-io/fyne-cross@latest
        - fyne-cross windows -arch=amd64 -output SteamUpdateManager
    skip: true

archives:
  - format: zip
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
    files:
      - LICENSE
      - README.md
    builds:
      - windows-amd64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'